[package]
name = "bansheelong_local"
version = "0.1.0"
edition = "2021"

[dependencies]
bansheelong_types = { path = "../types" }
chrono = "0.4.19"
image = "0.24.3"
imageproc = "0.23.0"
lazy_static = "1.4.0"
rusttype = "0.9.2"
